
services:
  db:
    image: nouchka/sqlite3  # image SQLite3
    container_name: sqlite_simplon_db
    volumes:
      - ./data:/root/db  # pour stocker la base sqlite3
    tty: true

  script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: script_runner
    depends_on:
      - db
    volumes:
      - ./data:/root/db  # ncessaire pour que le script accède au même dossier sinon pas de db